[package]
name = "simpler_easier_dtlc"
version = "0.1.0"
authors = ["egx <egx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
