[package]
name = "ch2"
version = "0.1.0"
authors = ["Evghenii <egx@egx-mbp.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.0"
